### PR TITLE
clear links / missing

### PR DESCRIPTION
**Pull request by aurochsen**

### CODE REVIEW

**Comment by jackbayliss** [comment]
Is this confirmed working?

**Comment by kaijehenstra** [comment]
It seems that it just clears the links so it can pull the new one's from the repo. In my opinion this should work.

**Comment by jackbayliss** [comment]
@kaijehenstra  Correct, I usually like to have it confirmed working before I merge- though I'm sure it'll be just fine :)

**Comment by aurochsen** [comment]
Yessir, tested on DE and US. Works fantastical.

**Comment by aurochsen** [comment]
@jackbayliss I'll give you $1 for a merge! =)

**Pull request merged**
