### PR TITLE
2 vehicles needed

### PR DESCRIPTION
**Pull request by meyerdominik**
If you are using LF20 as a main lf, you'll need 2 of them

### CODE REVIEW

**Comment by jackbayliss** [comment]
If this really required for all DE users? 🔢 @meyerdominik

**Review by jackbayliss — APPROVED** [review]
Looks fine, dunno if we need it though.

**Comment by meyerdominik** [comment]
@jackbayliss 

The mission requires 3000l of water and an avg. of 9 fireman.

The biggest lf that i know is the lf 20 with 9 fireman an 2000l of water. So you need at least two of them.
There are vehicles with more water, but they carry less firemann. 
Either way you need at least two.

**Comment by jackbayliss** [comment]
Cool, will merge it.

**Pull request merged**
