### PR TITLE
German umlaute

### PR DESCRIPTION
**Pull request by meyerdominik**
ä, ö, ü, Ä, Ö, Ü, ß

Hopefully I didn't miss any ^^

### CODE REVIEW

**Comment by jackbayliss** [comment]
Thanks mate, I will make this pull once I edit the generator- otherwise everyone will overwrite it 🥇

**Comment by meyerdominik** [comment]
I accidentally rebased the branch onto the current master ._. Just ignore the last commits ^^

**Comment by meyerdominik** [comment]
ok i fixed it xD

**Review by meyerdominik — COMMENTED** [review]
Merged #55

**Comment by jackbayliss** [comment]
FYI this will be pushed to all regions next patch see attached for sample output 
image

I'm planning on running a master generation of missions to fix it for all issued areas 👍🏻

**Comment by jackbayliss** [comment]
I've updated all the missions again- if you had to edit any please make a pull request- apologies in advance 👍🏻

**Pull request closed without merging**
